logging:
  level:
    com.example.todos: DEBUG
    org.springframework.beans: DEBUG
    org.springframework.web: TRACE

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:todos;NON_KEYWORDS=USER
    username: sa
    password: sa

site:
  author: "송연"
  description: "Spring Boot를 이용한 Todo List"